<?php date_default_timezone_set('Asia/Ho_Chi_Minh'); ?>
<div class="container-fluid">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="card card-plain">
                <div class="card-header card-header-primary tap-search">
                    <h4 class="card-title mt-0">Search</h4>
                </div>
                <div class="card-body tap-search-body">
                    <form method="POST" action="<?php echo $this->url('setting-day', ['action' => 'search']); ?>">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Day</label>
                                    <input type="text" class="form-control datepicker search" name="search" id="search" value="<?= date("m/d/Y") ?>">
                                </div>
                            </div>
                        </div>
                        <br>

                        <button type="submit" class="btn btn-primary">Search<div class="ripple-container"></div></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <h6>List</h6>
            <?php if (isset($messages)) : ?>
                <ul>
                    <?php foreach ($messages as $message) : ?>
                        <li><?= $message ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <button type="button" onclick="document.getElementById('modal-show').style.display = 'block'" class="btn btn-success"><span class="material-icons" style="color:#FFF">add</span> Set special day</button>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="">
                                <th>
                                    From day
                                </th>
                                <th>
                                    To day
                                </th>
                                <th>
                                    Type day
                                </th>
                                <th>
                                    Note
                                </th>
                                <th>
                                    Created at
                                </th>
                                <th>
                                    Created by
                                </th>
                                <th>
                                    Action
                                </th>
                            </thead>
                            <tbody>
                                <?php if (isset($settingDayList) && count($settingDayList) > 0) :
                                    foreach ($settingDayList as $sdl) :
                                ?>
                                        <tr>
                                            <td>
                                                <?= $sdl->from ?>
                                            </td>
                                            <td>
                                                <?= $sdl->to ?>
                                            </td>
                                            <td>
                                                <?php switch ($sdl->type) {
                                                    case 1: {
                                                            echo 'Saturday';
                                                            break;
                                                        }
                                                    case 2: {
                                                            echo 'Holiday';
                                                            break;
                                                        }
                                                    case 3: {
                                                            echo 'Any day';
                                                            break;
                                                        }
                                                }
                                                ?>
                                            </td>
                                            <td>
                                                <?= $sdl->note ?>
                                            </td>
                                            <td>
                                                <?= $sdl->created_at ?>
                                            </td>
                                            <td>
                                                <?= $sdl->getStaffName($sdl->create_by) ?>
                                            </td>
                                            <td>
                                                <a href="<?php echo 'setting-day/edit?id=' . $sdl->id ?>"><span class="material-icons btn-hover" style="color: #0190B0" title="Chỉnh sửa">edit</span></a>
                                                <a href="<?php echo 'setting-day/delete?id=' . $sdl->id ?>"><span class="material-icons btn-hover" style="color: red" title="Xoá">delete</span></a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div id="modal-show" class="modal-show1">
            <div class="modal-content-show2 animate-show">
                <div class="imgcontainer-close">
                    <span onclick="document.getElementById('modal-show').style.display = 'none'" class="close-show" title="Close Modal">&times;</span>
                </div>

                <div class="container-show">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" id="trang" href="javascript:;">Add special day</a>
                    </div>
                    <div class="card-body">
                        <form method="post" action="<?php echo $this->url('setting-day', ['action' => 'create']); ?>">
                            <div class="row mb-5">
                                <div class="col-md-12">
                                    <div class="form-check-inline">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="isHalfDay" value="0" checked onclick="display(0)">Whole day
                                        </label>
                                    </div>
                                    <div class="form-check-inline">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="isHalfDay" value="1" onclick="display(1)">Half day
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row" id="from-to-day">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">From day</label>
                                        <input type="text" class="form-control datepicker dpk" name="from_day" required="required" value="<?= date('m/d/Y') ?>">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">To day</label>
                                        <input type="text" class="form-control datepicker dpk" name="to_day" required="required" value="<?= date("m/d/Y") ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row" id="haft-day">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Day</label>
                                        <input type="text" class="form-control datepicker dpk" name="aDay" required="required" value="<?= date("m/d/Y") ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="type-day">Type day</label>
                                        <select class="form-control" id="type-day" name="type-day">
                                            <option value="1">Saturday</option>
                                            <option value="2">Holiday</option>
                                            <option value="3">Any day</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-check">
                                        <input class="offDay" type="checkbox" value="1" name="offDay"> Off day
                                    </div>
                                    <div class="form-group day-session">
                                        <div class="form-check-inline">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="day-session" value="2" checked>Morning
                                            </label>
                                        </div>
                                        <div class="form-check-inline">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="day-session" value="1">Afternoon
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Note</label>
                                        <textarea required="required" class="form-control" rows="5" name="note"></textarea>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Add day</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Get the modal
    var modal = document.getElementById('modal-show');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<script>
    function display(x) {
        if (x == 0) {
            $("#from-to-day").show(500);
            $("#haft-day").hide(500);
            $('.day-session').fadeOut('slow');
        } else {
            $("#from-to-day").hide(500);
            $("#haft-day").show(500);
            $('.day-session').fadeIn('slow');
        }
    }
</script>

<script>
    var dateToday = new Date();
    $(".dpk").datepicker({
        showButtonPanel: true,
        minDate: dateToday,
        changeMonth: false,
        changeYear: false,
    });

    $('.search').datepicker({
        changeMonth: true,
        changeYear: false,
        showButtonPanel: true,
        onClose: function(dateText, inst) {
            $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, inst.selectedDay));
        }
    });
</script>
