
<style>
    table.dataTable thead .sorting:after,
    table.dataTable thead .sorting:before,
    table.dataTable thead .sorting_asc:after,
    table.dataTable thead .sorting_asc:before,
    table.dataTable thead .sorting_asc_disabled:after,
    table.dataTable thead .sorting_asc_disabled:before,
    table.dataTable thead .sorting_desc:after,
    table.dataTable thead .sorting_desc:before,
    table.dataTable thead .sorting_desc_disabled:after,
    table.dataTable thead .sorting_desc_disabled:before {
        bottom: .5em;
    }
    #list-leave_wrapper .row:first-child{
        display:  none !important;
    }
</style>
<script>
    $(document).ready(function () {
        $('#list-leave').DataTable();
    });
</script>
<div class="container-fluid">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="card card-plain">
                <div class="card-header card-header-primary tap-search">
                    <h4 class="card-title mt-0">Search</h4>
                </div>
                <div class="card-body tap-search-body">
                    <form method="post">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Name</label>
                                    <input type="text" class="form-control" name="full_name" value="<?php echo (isset($this->param['full_name']) && !empty($this->param['full_name'])) ? $this->param['full_name'] : '' ?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Email</label>
                                    <input type="text" class="form-control" name="email" value="<?php echo (isset($this->param['email']) && !empty($this->param['email'])) ? $this->param['email'] : '' ?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Code</label>
                                    <input type="text" class="form-control" name="code" value="<?php echo (isset($this->param['code']) && !empty($this->param['code'])) ? $this->param['code'] : '' ?>">
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Department</label>
                                    <select class="form-control" name="department" id="department" title="Department">
                                        <option value="">---</option>
                                        <?php if (isset($this->list_department) && !empty($this->list_department)): foreach ($this->list_department as $item): ?>
                                                <option value="<?php echo $item['id'] ?>" <?php echo (isset($this->param['department']) && !empty($this->param['department']) && $this->param['department'] == $item['id']) ? 'selected' : ''; ?>><?php echo $item['name'] ?></option>
                                            <?php
                                            endforeach;
                                        endif;
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Team</label>
                                    <select class="form-control" name="team" id="team" title="team">
                                        <option value="">---</option>
                                        <?php if (isset($this->param['team']) && !empty($this->param['team'])): ?>
                                            <option value="<?php echo $this->param['team'] ?>" selected><?php echo $this->list_all_team_title[$this->param['team']] ?></option>
                                        <?php endif; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Title</label>
                                    <select class="form-control" id="title" name="title" title="title">
                                        <option value="">---</option>
                                        <?php if (isset($this->param['title']) && !empty($this->param['title'])): ?>
                                            <option value="<?php echo $this->param['title'] ?>" selected><?php echo $this->list_all_team_title[$this->param['title']] ?></option>
                                        <?php endif; ?>
                                    </select>
                                </div>
                            </div>

                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Month</label>
                                    <input type="text" class="form-control datepickermy" name="date" id="date" required="required" value="<?php echo (isset($this->param['date']) && !empty($this->param['date'])) ? $this->param['date'] : '' ?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Status : </label>
                                    <select class="form-control" name="status-leave" title="status">
                                        <option value="">All</option>
                                        <option value="1" <?php if(isset($this->param['status'])&&($this->param['status']!='')){echo ($this->param['status'] == 1)?'selected':'';}?>>Approved</option>
                                        <option value="0" <?php if(isset($this->param['status'])&&($this->param['status']!='')){echo ($this->param['status'] == 0)?'selected':'';}?>>Reject</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Search<div class="ripple-container"></div></button>
                        <button type="submit"  name="export-leave" value="1" class="btn btn-info">Export leave<div class="ripple-container"></div></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <h6>Xác nhận phép</h6>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="list-leave" class="table table-striped" cellspacing="0" width="100%">
                            <thead class="">
                            <th style="display: none">
                                
                            </th>
                            <th>
                                STT
                            </th>
                            <th>
                                Code
                            </th>
                           
                            <th>
                                Name
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Department
                            </th>
                            <th>
                                Team
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                From date
                            </th>
                            <th>
                                To Date
                            </th>
                            <th>
                                Số ngày
                            </th>
                            <th>
                                Nhóm phép
                            </th>
                            <th>
                                Loại phép
                            </th>
                            <th>
                                Reason
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Action
                            </th>
                            
                            </thead>
                            <tbody>
                                <?php $stt = 1; ?>
                                <?php if (isset($this->list_leave_detail) && !empty($this->list_leave_detail)):foreach ($this->list_leave_detail as $item): ?>
                                        <tr>
                                            <td style="display: none"><input   class="id-leave-detail" value="<?php echo $item['id'] ?>" ></td>
                                            <td><?php echo $stt++ ?></td>
                                            <td><?php echo $item['code'] ?></td>
                                            <td><?php echo $item['full_name'] ?></td>
                                            <td><?php echo $item['email']?></td>
                                            <td><?php echo $item['deparment'] ?></td>
                                            <td><?php echo $item['team'] ?></td>
                                            <td><?php echo $item['title'] ?></td>
                                            <td><?php echo date_create($item['from_date'])->format('m/d/Y') ?></td>
                                            <td><?php echo date_create($item['to_date'])->format('m/d/Y') ?></td>
                                            <td><?php echo $item['count_day'] ?></td>
                                            <td><?php echo $item['group_type'] ?></td>
                                            <td><?php echo $item['leave_type'] ?></td>
                                            <td><?php echo $item['reason'] ?></td>
                                            <td>
                                                <?php if ($item['status'] == 1): ?>
                                                    <span class="label label-success">APPROVED</span>
                                                <?php elseif ($item['status'] == 2): ?>
                                                    <span class="label label-warning">PEDDING</span>
                                                <?php else: ?>
                                                    <span class="label label-danger">REJECT</span>
                                            <?php endif; ?>
                                            </td>
                                            <td>
                                                <span class="material-icons btn-hover view_detail" style="color: gray" title="Chi tiết">visibility</span>
                                                <?php if ($this->info_user_team['department_id'] == DEPARTMENT_ADMIN): ?>
                                                    <span class="material-icons btn-hover  btn-del-leave" style="color: red" title="Xoá">clear</span>
                                            <?php endif; ?>
                                            </td>

                                        </tr>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div id="modal-show-detail" class="modal-show1">
            <div class="modal-content-show2 animate-show">
                <div class="imgcontainer-close">
                    <span onclick="document.getElementById('modal-show-detail').style.display = 'none'" class="close-show"
                          title="Close Modal">&times;</span>
                </div>

                <div class="container-show">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" id="trang" href="javascript:;">Detail</a><br><span class="bold" style="color: gray;font-size: 15px" id="info_staff">1651120140 - Huynh Cong Trang</span>
                    </div>
                    <div class="card-body">
                        <input id="id_leave2" name="id_leave2" class="hidden" value="">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group status-leave">
                                    <label class="bmd-label-floating">Trạng thái: </label>
                                    <span class="label label-warning label-status">PEDDING</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <h5>Detail handle by</h5>
                        </div>
                        <div class="row">
                            <div class="table-responsive table-status-main">
                                <table class="table  table-status">
                                    <thead class=" text-primary">
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Họ và tên
                                    </th>
                                    <th>
                                        Phòng ban
                                    </th>
                                    <th>
                                        Trạng thái
                                    </th>
                                    <th>
                                        Ngày tạo
                                    </th>
                                    <th>
                                        Note
                                    </th>
                                    </thead>
                                    <tbody class="data-status">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Get the modal
    var modal = document.getElementById('modal-show');
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<script>
    $(document).ready(function () {

        $('.view_detail').click(function () {
            //get info va trang thai, thong tin approve, reject
            var id_leave = $(this).parents('tr').find('.id-leave-detail').val();
            var id_leave = $(this).parents('tr').find('.id-leave-detail').val();
            $.ajax({
                method: "POST",
                url: "/leave-staff/show-leave",
                data: {
                    id_leave: id_leave
                }
            }).done(function (data) {
                var data_main = jQuery.parseJSON(data);
                console.log(data_main);
                $('#info_staff').text(data_main.data.codea_staff + " - " + data_main.data.full_name_staff);
                $('.label-status').remove();
                if (data_main.status == 0) {
                    $(".status-leave").append('<span class="label label-danger label-status">REJECT</span>');
                    $('.data-status').empty();
                    $('.table-status').show();
                    $(".note-leave-status").remove();
                    var stt = 1;
                    if (data_main.data.approve_by_leader != null) {
                        $('.data-status').append('<tr><td>' + (stt++) + '</td><td>' + data_main.data.approve_by_leader + '</td><td>' + data_main.data.department_leader + '</td><td><span class="label label-success">APPROVED</span></td><td>' + data_main.data.approve_at_leader + '</td><td></td></tr>')
                    }
                    if (data_main.data.code_reject != null) {
                        var string_temp = '<div><label class="bmd-label-floating">Lý do :</label><p class="text-justify">' + data_main.data.reason_reject + '</p></div><div><label class="bmd-label-floating">Note :</label><p class="text-justify">' + data_main.data.reason + '</p></div>';
                        $('.data-status').append('<tr><td>' + (stt++) + '</td><td>' + data_main.data.full_name_reject + '</td><td>' + data_main.data.department_reject + '</td><td><span class="label label-danger">Reject</span></td><td>' + data_main.data.create_at + '</td><td>' + string_temp + '</td></tr>')
                    }
                } else if (data_main.status == 1) {
                    $('.data-status').empty();
                    $('.table-status').show();
                    $(".note-leave-status").remove();
                    var stt = 1;
                    if (data_main.data.approve_by_leader != null) {
                        $('.data-status').append('<tr><td>' + (stt++) + '</td><td>' + data_main.data.approve_by_leader + '</td><td>' + data_main.data.department_leader + '</td><td><span class="label label-success">APPROVED</span></td><td>' + data_main.data.approve_at_leader + '</td><td></td></tr>')
                    }
                    if (data_main.data.approve_by_hr != null) {
                        $('.data-status').append('<tr><td>' + (stt++) + '</td><td>' + data_main.data.approve_by_hr + '</td><td>' + data_main.data.department_hr + '</td><td><span class="label label-success">APPROVED</span></td><td>' + data_main.data.approve_at_hr + '</td><td></td></tr>')
                    }
                    if (stt == 1) {
                        $('.table-status').hide();
                        $('.table-status-main').append('<p class="text-justify note-leave-status">Note : Chức danh này tự động approved </p>');
                    }
                    $(".status-leave").append('<span class="label label-success label-status">APPROVED</span>');
                }
                document.getElementById('modal-show-detail').style.display = 'block';
            });

        });


        $(".btn-del-leave").click(function () {
            var id_leave = $(this).parents('tr').find('.id-leave-detail').val();
            Swal.fire({
                title: 'Bạn có chắc chắn ?',
                text: "Xoá phép này không",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        method: "POST",
                        url: "/leave-staff/del-leave",
                        data: {
                            id_leave: id_leave
                        }
                    }).done(function (data) {
                        if (data == 1) {
                            Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                    ).then((result) => {
                                location.reload();
                            });
                        } else {
                            Swal.fire(
                                    'Cancelled',
                                    'Error',
                                    'error'
                                    )
                        }
                    });

                }
            })
        });
        
        //get team by department
        $('#department').change(function () {
            var department = $('#department').val();
            if (department == "") {
                $("#team").empty();
                $("#team").append("<option value = ''>---</option>");
                $("#title").empty();
                $("#title").append("<option value = ''>---</option>");
                return false;
            } else {
                $.ajax({
                    method: "POST",
                    url: "/list-approve/get-team-or-title",
                    data: {
                        parent_id : department
                    }
                }).done(function (data) {
                    var data_main = jQuery.parseJSON(data);
                    console.log(data_main);
                    $("#team").empty();
                    $("#team").append("<option value = ''>---</option>");
                    $.each(data_main, function (index, value) {
                        $("#team").append("<option value = '"+value.id+"'>"+value.name+"</option>");
                    });
                });
            }
        });
        
        
        //get title by team
        $('#team').change(function () {
            var team = $('#team').val();
            if (team == "") {
                $("#title").empty();
                $("#title").append("<option value = ''>---</option>");
                return false;
            } else {
                $.ajax({
                    method: "POST",
                    url: "/list-approve/get-team-or-title",
                    data: {
                        parent_id : team
                    }
                }).done(function (data) {
                    var data_main = jQuery.parseJSON(data);
                    console.log(data_main);
                    $("#title").empty();
                    $("#title").append("<option value = ''>---</option>");
                    $.each(data_main, function (index, value) {
                        $("#title").append("<option value = '"+value.id+"'>"+value.name+"</option>");
                    });
                });
            }
        });
    })
</script>