<div class="container-fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">1651120140 - Huỳnh Công Trang</h4>
                        <p class="card-category">PHP Dev</p>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Month</label>
                                        <input type="text" class="form-control date" value="03/2020">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary pull-right">Search</button>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h6>Statastic timing</h6>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="">
                                <th>
                                    Số ngày đi làm
                                </th>
                                <th>
                                    Số ngày nghĩ
                                </th>
                                <th>
                                    Số lần quên chấm công
                                </th>
                                <th>
                                    Tổng thời gian đi trể
                                </th>
                                <th>
                                    Số ngày phạt
                                </th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            1
                                        </td>
                                        <td>
                                            2
                                        </td>
                                        <td>
                                            3
                                        </td>
                                        <td>
                                            4
                                        </td>
                                        <td>
                                            5
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h6>Dashboard my timing</h6>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="text-primary">
                                <th>
                                    Ngày
                                </th>
                                <th>
                                    Giờ vào
                                </th>
                                <th>
                                    Giờ ra
                                </th>
                                <th>
                                    Ngày làm
                                </th>
                                <th>
                                    Lý do
                                </th>
                                <th>
                                    Ghi chú
                                </th>
                                <th>
                                    Hành động
                                </th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            MonDay , 28-03-2020
                                        </td>
                                        <td>
                                            17:15
                                        </td>
                                        <td>
                                            16:23
                                        </td>
                                        <td>
                                            1 day
                                        </td>
                                        <td>

                                        </td>
                                        <td>

                                        </td>
                                        <td>
                                            <div class="dropdown show">
                                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Action
                                                </a>

                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                    <a class="dropdown-item" href="#">Bổ sung công</a>
                                                    <a class="dropdown-item" href="#">Đăng kí phép</a>
                                                    <a class="dropdown-item" href="#">Xác nhận đi trể/về sớm</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>