<?php
function isWeekend($date) {
    $weekDay = date('w', strtotime($date));
    return ($weekDay == 0);
}
function findKeyValue($key,$value,$data){
    foreach ($data as $item){
        if($item[$key] == $value){
            return $item;
        }
    }
    return '';
}
function getTotalHours(DateInterval $int){
    return ($int->d * 24) + $int->h + $int->i / 60;
}
?>
<div class="container-fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">1651120140 - Huỳnh Công Trang</h4>
                        <p class="card-category">PHP Dev</p>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Month</label>
                                        <input type="text" class="form-control date" value="03/2020">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary pull-right">Search</button>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h6>Statastic timing</h6>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="">
                                <th>
                                    Số ngày đi làm
                                </th>
                                <th>
                                    Số ngày nghĩ
                                </th>
                                <th>
                                    Số lần quên chấm công
                                </th>
                                <th>
                                    Tổng thời gian đi trể
                                </th>
                                <th>
                                    Số ngày phạt
                                </th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            1
                                        </td>
                                        <td>
                                            2
                                        </td>
                                        <td>
                                            3
                                        </td>
                                        <td>
                                            4
                                        </td>
                                        <td>
                                            5
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h6>Dashboard my timing</h6>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="text-primary">
                                <th>
                                    Ngày
                                </th>
                                <th>
                                    Giờ vào
                                </th>
                                <th>
                                    Giờ ra
                                </th>
                                <th>
                                    Ngày làm
                                </th>
                                <th>
                                    Lý do
                                </th>
                                <th>
                                    Ghi chú
                                </th>
                                <th>
                                    Hành động
                                </th>
                                </thead>
                                <tbody>
                                    <?php if(isset($this->all_date)) foreach ($this->all_date as $item):?>
                                    <tr <?php if(isWeekend($item['Date'])){
                                        echo 'class="background-break" title="Hôm nay là chủ nhật"';
                                    }else if(in_array($item['Date'], $this->day_all_advance) && $this->day_advance[$item['Date']] == 0){
                                        echo 'class="background-break" title="Hôm nay là ngày nghĩ"';
                                    }else if(in_array($item['Date'], $this->day_all_advance) && $this->day_advance[$item['Date']] != 0){
                                        echo 'class="background-break" title="Hôm nay được nghĩ nữa ngày"';
                                    }?>>
                                        <?php 
                                            $check_in_at = '' ;
                                            $check_out_at = '' ;
                                            $count_work = '' ;
                                            $reason = '' ;
                                            $note = '' ;
                                            $img_temp1 = '';
                                            $img_temp2 = '';
                                            $action = array();//1,2,3: bosungcong,dangkiphep,xacnhantresom
                                        ?>
                                        <?php if(isset($this->detail_timing[$item['Date']])){
                                            $find = findKeyValue('type', 1, $this->detail_timing[$item['Date']]);
                                            if(!empty($find)){
                                                
                                                $check_in_at = $find['check_in_at'];
                                                $check_out_at = $find['check_out_at'];
                                                
                                                if(!empty($find['img1']) && !empty($check_in_at)){
                                                    $img_temp1 = '<div class="row"><img class="rounded" width="70px" src="'.HOST.'photo/pg-check-in/'.$find['img1'].'"></div>';
                                                }
                                                
                                                if(!empty($find['img2']) && !empty($check_out_at)){
                                                    $img_temp2 = '<div class="row"><img class="rounded" width="70px" src="'.HOST.'photo/pg-check-in/'.$find['img2'].'"></div>';
                                                }
                                                
                                                if(!empty($check_in_at) && !empty($check_out_at)){// tinh so ngay cong neu check in
                                                    $check_in_temp = '';
                                                    $type_check_in = 0;
                                                    $type_check_out = 0;
                                                    $check_out_temp = '';
                                                    if((date_create($check_in_at) > date_create($this->shift_stafff['begin_break_time']))&&(date_create($check_in_at) < date_create($this->shift_stafff['end_break_time']))){
                                                        $type_check_in = 1;
                                                        $check_in_temp = $this->shift_stafff['end_break_time'];
                                                    }else if(date_create($check_in_at) < date_create($this->shift_stafff['begin'])){
                                                        $type_check_in = 2;
                                                        $check_in_temp = $this->shift_stafff['begin'];
                                                    }else {
                                                        $type_check_in = 3;
                                                        $check_in_temp = $check_in_at;
                                                    }
                                                        
                                                    
                                                    if((date_create($check_out_at) > date_create($this->shift_stafff['begin_break_time']))&&(date_create($check_out_at) < date_create($this->shift_stafff['end_break_time']))){
                                                        $type_check_out = 1;
                                                        $check_out_temp = $this->shift_stafff['begin_break_time'];
                                                    }else if(date_create($check_out_at) > date_create($this->shift_stafff['end'])){
                                                        $type_check_out = 2;
                                                        $check_out_temp = $this->shift_stafff['end'];
                                                    }else {
                                                        $type_check_out = 3;
                                                        $check_out_temp = $check_out_at;
                                                    }
                                                    
                                                    if($type_check_in != 1 && $type_check_out != 1){
                                                        $time_break = date_diff(date_create($this->shift_stafff['begin_break_time']),date_create($this->shift_stafff['end_break_time']));
                                                        $total_count_time = date_diff(date_create($check_in_temp), date_create($check_out_temp));
                                                        $count_time = getTotalHours($total_count_time) - getTotalHours($time_break);
                                                        if($count_time >= 6){
                                                            $count_work = '1 ngày công ';
                                                        }else if($count_time >= 3){
                                                            $count_work = '0.5 ngày công';
                                                        }
                                                    }else {
                                                        $total_count_time = date_diff(date_create($check_in_temp), date_create($check_out_temp));
                                                        $count_time = getTotalHours($total_count_time);
                                                        if($count_time >= 6){
                                                            $count_work = '1 ngày công ';
                                                        }else if($count_time >= 3){
                                                            $count_work = '0.5 ngày công';
                                                        }
                                                    }
                                                }
                                                $find_late = findKeyValue('type', 4, $this->detail_timing[$item['Date']]);
                                                if(!empty($find_late)){
                                                    $reason = $find_late['reason'];
                                                    $note = $find_late['note'];
                                                }
                                                //phan sau tinh gio
                                            }else {
                                                $find_leave = findKeyValue('type',2, $this->detail_timing[$item['Date']]);
                                                if(!empty($find_leave) && $find_leave['ngay_cong']!=0){
                                                    $count_work = $find_leave['ngay_cong'].' ngày phép';
                                                    $reason = $find_leave['reason'];
                                                    $note = $find_leave['note'];
                                            }else {
                                                    $find_temp = findKeyValue('type',3, $this->detail_timing[$item['Date']]);
                                                    if(!empty($find_temp) && $find_temp['ngay_cong']!=0){
                                                        $count_work = 'Bổ sung '.$find_temp['ngay_cong'].' ngày';
                                                        $reason = $find_temp['reason'];
                                                        $note = $find_temp['note'];
                                                    }
                                                }
                                            }
                                            
                                        }?>
                                        <td>
                                            <?php echo date_format(date_create($item['Date']), 'l, d-m-Y')?>
                                        </td>
                                        <td>
                                            <?php echo $img_temp1.$check_in_at?>
                                        </td>
                                        <td>
                                            <?php echo $img_temp2.$check_out_at?>
                                        </td>
                                        <td>
                                            <?php echo $count_work?>
                                        </td>
                                        <td>
                                            <?php echo $reason?>
                                        </td>
                                        <td>
                                            <?php echo $note?>
                                        </td>
                                        <td>
                                            <div class="dropdown show">
                                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Action
                                                </a>

                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                    <a class="dropdown-item" href="#">Bổ sung công</a>
                                                    <a class="dropdown-item" href="#">Đăng kí phép</a>
                                                    <a class="dropdown-item" href="#">Xác nhận đi trể/về sớm</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>