<div class="container-fluid">

    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">person</i>
                    </div>
                    <p class="card-category">Staff total</p>
                    <h3 class="card-title"><?= $staffTotal ?></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">group</i>
                    </div>
                    <p class="card-category">Team total</p>
                    <h3 class="card-title"><?= $teamTotal ?></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-danger card-header-icon">
                    <div class="card-icon">
                        <i class="fa fa-building"></i>
                    </div>
                    <p class="card-category">Office total</p>
                    <h3 class="card-title"><?= $officeTotal ?></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-info card-header-icon">
                    <div class="card-icon">
                        <i class="fa fa-user"></i>
                    </div>
                    <p class="card-category">User total</p>
                    <h3 class="card-title"><?= $userTotal ?></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-success">
                    <div class="ct-chart" id="dailySalesChart"></div>
                    <div id="leaveTotalChart" style="display: none;">
                        <?php echo $leaveTotalCurrentMonth ?>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Leave total in the last 5 months</h4>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">access_time</i> updated 4 minutes ago
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-warning">
                    <div class="ct-chart" id="websiteViewsChart"></div>
                    <div id="timeLateTotalChart" style="display: none;">
                        <?php echo $timeLateTotalCurrentMonth ?>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Time late total in last 5 months</h4>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">access_time</i> updated 4 minutes ago
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-danger">
                    <div class="ct-chart" id="completedTasksChart"></div>
                    <div id="staffTempTotalChart" style="display: none;">
                        <?php echo $staffTempTotalCurrentMonth ?>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Staff temp total in last 5 months</h4>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">access_time</i> updated 4 minutes ago
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-12">
            <div class="card">
                <div class="card-header card-header-warning">
                    <h4 class="card-title">Top 4 diligent staff</h4>
                    <p class="card-category">April, 2020</p>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-warning">
                            <th>Code</th>
                            <th>Name</th>
                            <th>Team</th>
                            <th>Deparment</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>A122</td>
                                <td>Dakota Rice</td>
                                <td>Tech-1</td>
                                <td>IT</td>
                            </tr>
                            <tr>
                                <td>A345</td>
                                <td>Minerva Hooper</td>
                                <td>Tech-1</td>
                                <td>IT</td>
                            </tr>
                            <tr>
                                <td>A225</td>
                                <td>Sage Rodriguez</td>
                                <td>HR-2</td>
                                <td>HR</td>
                            </tr>
                            <tr>
                                <td>A334</td>
                                <td>Philip Chaney</td>
                                <td>Fire</td>
                                <td>Business</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Initialize a Line chart in the container with the ID chart1
    new Chartist.Line('#chart1', {
        labels: [1, 2, 3, 4],
        series: [
            [100, 120, 180, 200]
        ]
    });

    // Initialize a Line chart in the container with the ID chart2
    new Chartist.Bar('#chart2', {
        labels: [1, 2, 3, 4],
        series: [
            [5, 2, 8, 3]
        ]
    });
</script>